# pre commit hook config
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
      stages: [commit]
    - id: end-of-file-fixer
      stages: [commit]
    - id: trailing-whitespace
      stages: [commit]
    - id: detect-private-key
      stages: [commit]
    - id: check-added-large-files
      stages: [commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
    - id: ruff
      types_or: [ python, pyi ]
      stages: [commit]
      args: [ --fix, --unsafe-fixes ]
    - id: ruff-format
      stages: [commit]
      types_or: [ python, pyi ]
